### ISSUE TITLE
Dont work in CHROME

### ISSUE THREAD

**Issue by camillemonchicourt** [PnCevennes/angular_simple_map#1]
![simple_map_chrome](https://cloud.githubusercontent.com/assets/4418840/11746491/b3df72ae-a01e-11e5-88c5-af18ba6c7cd7.jpg)

Same for PQ.

**Comment by amandine-sahl** [comment]
Ca ne marche pas sous Chrome du fait que ce soit une ressource externe. Par défaut Chrome n'autorise pas les cross origin request. 
Il faut soit que  tu installe le tout sur un serveur soit que tu lance chrome de la façon suivante : 
chrome.exe --allow-file-access-from-files --disable-web-security

**Comment by camillemonchicourt** [comment]
Oh OK I see !
